const LABS=[{id:'builder',name:'Connectivity Solution Builder',description:'Explore which technologies could connect your community — and understand why.',time:'3–5 min',level:'Beginner',icon:'⌘'},{id:'tower',name:'Can You See the Tower?',description:'Discover how terrain, antenna height and line of sight shape a wireless link.',time:'2–3 min',level:'Beginner / Intermediate',icon:'⌁'},{id:'cost',name:'Connectivity Cost Challenge',description:'Balance upfront costs, ongoing expenses and resilience in a practical challenge.',time:'5–8 min',level:'Intermediate',icon:'◈'}];
const STEPS=[
 {title:'What are you connecting?',hint:'Every connection starts with people. Choose the place you have in mind.',fields:[{key:'site',options:['School','Health facility','Community center','Small community','Other']}]},
 {title:'How many people will use the connection?',hint:'This helps estimate connectivity demand. The number online at once and their activities matter too.',fields:[{key:'users',options:['Fewer than 50','50–200','200–500','500–1,000','More than 1,000']}]},
 {title:'What infrastructure is nearby?',hint:'Existing infrastructure can open up possibilities. It’s fine to choose Unknown.',fields:[{key:'fiber',label:'Nearest fiber connection',why:'fiber',options:['Less than 1 km','1–5 km','5–20 km','More than 20 km','Unknown']},{key:'mobile',label:'Nearest mobile network',why:'fwa',options:['Strong 4G/5G coverage','Weak/intermittent coverage','No coverage','Unknown']},{key:'tower',label:'Nearest telecom tower',why:'los',options:['Less than 5 km','5–15 km','15–30 km','More than 30 km','Unknown']}]},
 {title:'What is the terrain like?',hint:'The landscape affects construction and how radio signals travel.',why:'terrain',fields:[{key:'terrain',options:['Flat/open','Hilly','Mountainous','Dense urban','Dense vegetation','Unknown']}]},
 {title:'How reliable is electricity?',hint:'A connection only works while its equipment has power.',why:'power',fields:[{key:'power',options:['Reliable grid','Grid available but unreliable','No grid electricity','Unknown']}]},
 {title:'What matters most?',hint:'Choose one or two priorities. Every approach involves trade-offs.',why:'tco',fields:[{key:'priorities',multi:true,options:['Lowest initial cost','Lowest long-term cost','Fastest deployment','Highest capacity','Highest reliability','Easy local maintenance']}]}
];
const EXPLAIN={fiber:['Why does distance to fiber matter?','Longer routes often mean more trenching, poles, permits and installation work.','A nearby cable is not automatically an available service. Confirm a usable connection point, provider access and the actual construction route.'],fwa:['What is FWA?','Fixed Wireless Access uses a mobile network to provide broadband to a fixed location through a router.','Performance depends on signal quality, spectrum, congestion and service terms. An outdoor antenna may help in some locations.'],los:['Why does line of sight matter?','Point-to-point wireless usually needs a clear path between antennas.','The Fresnel zone is a volume around that path that also needs sufficient clearance. Tower visibility alone is not enough: frequency, terrain, vegetation, Earth curvature and link budget matter.'],terrain:['Why does terrain affect wireless?','Hills, buildings and trees can block or weaken radio signals.','Higher antennas or relay sites may help, but add infrastructure, power and maintenance. A survey is needed to check the full path.'],power:['Why does electricity reliability matter?','Routers, radios and local Wi-Fi all need electricity.','Size batteries or solar for equipment load and outage duration. Upstream equipment also needs resilient power.'],backhaul:['What is backhaul?','Backhaul carries traffic from a local access network toward the wider Internet.','A tower can receive fiber backhaul and use a radio link to reach a school. Wi-Fi and Ethernet distribute the connection locally.'],tco:['What is TCO?','Total cost of ownership includes setup and the ongoing cost of keeping a service working.','Compare construction and equipment (CAPEX) with service fees, electricity, repairs, replacements and support (OPEX) over the same period.']};
const TECH={fiber:{name:'Fiber',speed:'Slower with civil works',capacity:'Very high',cost:'Route-dependent',pros:['Very high capacity','Long lifetime','No radio interference'],cons:['Civil works can be expensive','Permits and construction take time'],path:['Internet','Provider fiber network','Site fiber terminal / router','Local Wi-Fi / Ethernet','Users']},fwa:{name:'4G/5G Fixed Wireless Access',speed:'Fast if service available',capacity:'Variable / potentially high',cost:'Low–medium setup + fees',pros:['Fast deployment','Reuses mobile infrastructure','Limited construction'],cons:['Coverage and congestion affect performance','Service plans may limit data'],path:['Internet','Mobile network backhaul','4G/5G FWA router','Local Wi-Fi / Ethernet','Users']},microwave:{name:'Point-to-point microwave / wireless',speed:'Survey-dependent',capacity:'Potentially high',cost:'Medium / site-dependent',pros:['High capacity on suitable paths','Avoids trenching','Extends backhaul to remote sites'],cons:['Needs path and Fresnel-zone clearance','Requires equipment, power and permission at both ends'],path:['Internet','Provider backhaul (e.g. fiber)','Tower → radio link → site router','Local Wi-Fi / Ethernet','Users']},leo:{name:'LEO satellite',speed:'Very fast if available',capacity:'Variable / shared',cost:'Equipment + service fees',pros:['Reaches very remote locations','Little terrestrial construction','Can complement terrestrial links'],cons:['Needs a clear view of the sky','Recurring costs and local power remain'],path:['Internet','Satellite provider network','LEO satellite → terminal / router','Local Wi-Fi / Ethernet','Users']}};

