// Qualitative rules: editable separately from UI. Weights are not performance estimates.
const RULES=[{tech:'fiber',field:'fiber',weights:[5,3,0,-3,-1],why:'Distance influences construction effort.'},{tech:'fwa',field:'mobile',weights:[5,0,-20,-2],why:'FWA needs usable mobile coverage and capacity.'},{tech:'microwave',field:'tower',weights:[3,2,0,-3,-2],why:'Tower proximity suggests a possible endpoint, not confirmed service.'},{tech:'microwave',field:'terrain',weights:[1,-1,-2,-2,-2,-1],why:'Terrain affects radio-path clearance.'}];
const PRIORITIES={'Lowest initial cost':[-1,2,0,1],'Lowest long-term cost':[2,0,1,-1],'Fastest deployment':[-1,2,0,2],'Highest capacity':[2,0,1,0],'Highest reliability':[1,0,0,0],'Easy local maintenance':[0,1,-1,0]};
function recommend(a){
 const keys=Object.keys(TECH),scores={fiber:0,fwa:0,microwave:0,leo:1},trace=['LEO starts at +1 for remote reach, conditional on service availability and clear sky.'];
 RULES.forEach(r=>{const f=STEPS.flatMap(s=>s.fields).find(f=>f.key===r.field),n=r.weights[f.options.indexOf(a[r.field])]||0;scores[r.tech]+=n;trace.push(`${TECH[r.tech].name}: ${a[r.field]} → ${n>0?'+':''}${n}. ${r.why}`);});
 (a.priorities||[]).forEach(p=>keys.forEach((k,i)=>{const n=PRIORITIES[p][i];scores[k]+=n;if(n)trace.push(`${p}: ${TECH[k].name} ${n>0?'+':''}${n}.`);}));
 const eligible=k=>!(k==='fwa'&&a.mobile!=='Strong 4G/5G coverage')&&!(k==='fiber'&&a.fiber==='Unknown')&&!(k==='microwave'&&(['Unknown','More than 30 km'].includes(a.tower)||a.terrain==='Unknown'));
 const ranked=keys.sort((x,y)=>scores[y]-scores[x]),primary=ranked.find(eligible)||'leo';
 const rating=k=>k==='fwa'&&a.mobile==='No coverage'?'Not currently viable':k==='fwa'&&a.mobile!=='Strong 4G/5G coverage'?'Needs verification':k==='fiber'&&a.fiber==='Unknown'?'Needs verification':k==='microwave'?'Survey-dependent':k==='leo'?'Conditional':scores[k]>=4?'Promising':scores[k]>=1?'Possible':'Less suitable';
 const reasons={fiber:[`You placed fiber ${a.fiber.toLowerCase()} away; investigate a usable connection and route.`,'Fiber offers substantial capacity and room for long-term growth.'],fwa:['You reported strong mobile coverage, so existing infrastructure may be reusable.','Installation can be faster than constructing a new fiber route.'],microwave:[`A tower ${a.tower.toLowerCase()} away may provide a useful endpoint.`,'A viable surveyed path can extend upstream backhaul without trenching the whole route.'],leo:['Satellite is worth exploring given your infrastructure and priorities.','It can reach remote locations without a new terrestrial last-mile route.']};
 const checks=['Confirm provider service, actual capacity, installation costs and local support.'];
 if(primary==='microwave')checks.push('Confirm tower access, backhaul, power, line of sight and Fresnel clearance. Proximity alone does not establish a link.');
 if(primary==='leo')checks.push('Verify authorized service availability, sky clearance, equipment availability and recurring capacity costs.');
 if(a.power!=='Reliable grid')checks.push(a.power==='No grid electricity'?'Include a sized solar/battery or other independent power system.':'Check power conditions and plan backup power at the site and upstream.');
 if(['200–500','500–1,000','More than 1,000'].includes(a.users))checks.push('Estimate simultaneous users and application demand. Multiple links and managed local distribution may be required.');
 if(Object.values(a).includes('Unknown'))checks.push('Unknown answers make this provisional. Verify infrastructure before selecting a service.');
 if(a.priorities.includes('Highest reliability'))checks.push('Explore an independent second link with failover. Shared power and routes can undermine redundancy.');
 return {primary,ranked,scores,trace,rating,reasons:reasons[primary],checks,lessons:[['Distance matters.',`Fiber is ${a.fiber.toLowerCase()} away in your scenario. The usable connection point and construction route determine feasibility.`],[a.mobile==='Strong 4G/5G coverage'?'Coverage can be reused.':'Wireless needs evidence.',a.mobile==='Strong 4G/5G coverage'?'Mobile infrastructure can support FWA, but signal strength does not establish available capacity.':'A tower or map is a starting point. Verify signal, path clearance and service availability.'],['Backhaul matters.','Upstream connectivity reaches the Internet; Wi-Fi and Ethernet distribute it to local users.'],[a.power==='Reliable grid'?'Think beyond setup cost.':'Power is part of connectivity.',a.power==='Reliable grid'?'Service fees, energy, support and replacement equipment all contribute to total cost of ownership.':'Include power generation or backup in the design and budget where needed.']]};
}
