const LEARN_CATEGORIES=['All','Connectivity','Wireless','Wi-Fi','Networking','Power','Economics & Resilience'];
const LEARN_CONCEPTS=[
{id:'connectivity',term:'Connectivity',definition:'The ability of people, devices or locations to communicate through a network and access digital services. Infrastructure, capacity, power, affordability and local networks all matter.',categories:['Connectivity'],labs:['builder','cost'],keywords:'network access digital inclusion'},
{id:'access-network',term:'Access network / Last mile',definition:'The part of a network that connects an end user or location to the wider telecommunications network. Fiber, FWA and satellite can provide access connectivity in different situations.',categories:['Connectivity'],labs:['builder'],keywords:'last mile'},
{id:'backhaul',term:'Backhaul',definition:'The connection that carries traffic from an access or local network toward the wider network or Internet. Fiber, microwave/P2P and satellite can all be used for backhaul.',categories:['Connectivity','Wireless'],labs:['builder','tower'],keywords:'upstream transport'},
{id:'fiber',term:'Fiber',definition:'A cable that carries information using light through optical fibers. Fiber can provide very high capacity and long-term scalability, but deployment may require significant civil works.',categories:['Connectivity'],labs:['builder','cost'],keywords:'optical cable'},
{id:'fwa',term:'Fixed Wireless Access (FWA)',definition:'Broadband delivered wirelessly between a mobile/radio network and a fixed location such as a school, business or home.',categories:['Connectivity','Wireless'],labs:['builder','cost','power'],keywords:'4g 5g'},
{id:'p2p',term:'Point-to-Point (P2P) wireless',definition:'A dedicated wireless link connecting two locations, often using directional antennas. A suitable radio path and sufficient clearance are important.',categories:['Connectivity','Wireless'],labs:['builder','tower','cost'],keywords:'point to point bridge'},
{id:'microwave',term:'Microwave',definition:'Radio technology commonly used for high-capacity point-to-point links. Distance, frequency, line of sight and path clearance all matter.',categories:['Wireless'],labs:['tower'],keywords:'radio link'},
{id:'satellite',term:'Satellite',definition:'Connectivity provided through satellites rather than terrestrial infrastructure. It can reach remote locations, but capacity, cost, latency and power requirements should be considered.',categories:['Connectivity','Power'],labs:['builder','cost','power'],keywords:'space'},
{id:'leo',term:'LEO satellite',definition:'Satellite connectivity using satellites in Low Earth Orbit. Their lower altitude can provide lower latency than traditional geostationary systems.',categories:['Connectivity','Wireless'],labs:['builder','power'],keywords:'low earth orbit'},
{id:'los',term:'Line of Sight (LOS)',definition:'An unobstructed direct path between two antennas. Seeing the other antenna does not always guarantee a reliable link.',categories:['Wireless'],labs:['tower'],keywords:'visibility path'},
{id:'fresnel',term:'Fresnel zone',definition:'The area around the direct radio path that should remain sufficiently clear of obstacles. A link can have visual LOS and still perform poorly if this zone is obstructed.',categories:['Wireless'],labs:['tower'],keywords:'clearance'},
{id:'frequency',term:'Frequency',definition:'The rate at which a radio signal oscillates, measured in hertz. Different bands have different propagation characteristics and regulatory uses.',categories:['Wireless','Wi-Fi'],labs:['tower','wifi'],keywords:'hz spectrum'},
{id:'coverage',term:'Coverage',definition:'The area where a network or wireless signal can provide useful service. Good coverage does not necessarily mean enough capacity for all users.',categories:['Connectivity','Wireless','Wi-Fi'],labs:['builder','wifi'],keywords:'signal reach'},
{id:'capacity',term:'Capacity',definition:'How much traffic a network can support. Excellent coverage can still become congested when many users share capacity.',categories:['Connectivity','Wi-Fi'],labs:['builder','cost','wifi'],keywords:'traffic users congestion'},
{id:'bandwidth',term:'Bandwidth',definition:'The amount of communication capacity available on a connection, commonly expressed in Mbps or Gbps. It is often shared between users and applications.',categories:['Connectivity','Wi-Fi'],labs:['builder','wifi'],keywords:'data rate'},
{id:'data-rates',term:'Mbps / Gbps',definition:'Units commonly used to describe data rates. Mbps means megabits per second; 1 Gbps equals 1,000 Mbps.',categories:['Connectivity','Wi-Fi'],labs:['builder','wifi'],keywords:'megabits gigabits per second data rate'},{id:'latency',term:'Latency',definition:'The time it takes data to travel through a network and receive a response. Low latency matters for interactive applications such as calls.',categories:['Connectivity'],labs:['builder','cost'],keywords:'delay'},
{id:'wifi',term:'Wi-Fi',definition:'A wireless technology used to connect nearby devices to a local network. Wi-Fi access does not necessarily mean Internet access is working.',categories:['Wi-Fi','Networking'],labs:['wifi','network'],keywords:'wireless lan'},
{id:'ap',term:'Access Point (AP)',definition:'A device that allows Wi-Fi devices to connect to a local network. Placement, frequency, obstacles and users affect the experience.',categories:['Wi-Fi','Networking'],labs:['wifi','network'],keywords:'wireless access point'},
{id:'wifi-bands',term:'2.4 GHz / 5 GHz / 6 GHz',definition:'Frequency bands used by Wi-Fi. 2.4 GHz generally reaches farther, while 5 and 6 GHz provide additional spectrum under suitable conditions.',categories:['Wi-Fi','Wireless'],labs:['wifi'],keywords:'band spectrum'},
{id:'wifi-channel',term:'Wi-Fi channel',definition:'A portion of a Wi-Fi band used for communication. Nearby APs using competing channels can interfere or contend.',categories:['Wi-Fi'],labs:['wifi'],keywords:'channel planning'},
{id:'interference',term:'Interference',definition:'Unwanted radio energy that can reduce wireless performance, from nearby networks, radio systems or devices.',categories:['Wireless','Wi-Fi'],labs:['tower','wifi'],keywords:'contention noise'},
{id:'wifi-generations',term:'Wi-Fi generations',definition:'Wi-Fi 5, 6, 6E and 7 offer different capabilities and band support. Newer Wi-Fi does not automatically mean better connectivity in every situation.',categories:['Wi-Fi'],labs:['wifi'],keywords:'wifi5 wifi6 wifi6e wifi7'},
{id:'ethernet',term:'Ethernet',definition:'A widely used technology for connecting devices through wired local networks, including APs, switches, routers and computers.',categories:['Networking'],labs:['network'],keywords:'wired lan'},
{id:'lan',term:'LAN — Local Area Network',definition:'A network connecting devices within a limited area such as a building or campus. Same-LAN devices may communicate without using the Internet.',categories:['Networking'],labs:['network'],keywords:'local network'},
{id:'wan',term:'WAN — Wide Area Network',definition:'A network connecting networks across larger geographic areas. In Lab 06, WAN represents connectivity beyond the local network toward the Internet.',categories:['Networking'],labs:['network'],keywords:'wide network'},
{id:'internet',term:'Internet',definition:'The global system of interconnected IP networks. Wi-Fi is local access; the Internet is what that network may ultimately reach.',categories:['Connectivity','Networking'],labs:['network'],keywords:'wan web'},
{id:'ip-address',term:'IP address',definition:'A numerical address used to identify a device or network interface in an IP network. Devices need appropriate configuration to communicate.',categories:['Networking'],labs:['network'],keywords:'ip'},
{id:'ipv4',term:'IPv4',definition:'The version of IP used for addresses such as 192.168.1.25. Lab 06 uses IPv4 for compact examples.',categories:['Networking'],labs:['network'],keywords:'ip address'},
{id:'ipv6',term:'IPv6',definition:'A newer version of IP with a vastly larger address space. Its format differs, but addressing and routing remain fundamental.',categories:['Networking'],labs:['network'],keywords:'ip'},
{id:'subnet',term:'Subnet',definition:'A logical group of IP addresses belonging to the same IP network. Devices on the same subnet can normally communicate locally.',categories:['Networking'],labs:['network'],keywords:'24 local'},
{id:'subnet-mask',term:'Subnet mask',definition:'Information that helps a device determine which part of an IPv4 address identifies its network. 255.255.255.0 corresponds to /24 here.',categories:['Networking'],labs:['network'],keywords:'mask cidr'},
{id:'switch',term:'Switch',definition:'A device that connects devices within a local Ethernet network and forwards traffic toward the appropriate destination.',categories:['Networking'],labs:['network'],keywords:'lan ethernet'},
{id:'router',term:'Router',definition:'A device that connects different IP networks. In Lab 06 it connects the local network to the upstream/WAN side.',categories:['Networking'],labs:['network'],keywords:'gateway routing'},
{id:'gateway',term:'Default gateway',definition:'The router a device uses to send traffic outside its local IP network. A wrong gateway can leave local communication working while blocking remote destinations.',categories:['Networking'],labs:['network'],keywords:'router remote'},
{id:'dhcp',term:'DHCP',definition:'A service that automatically provides settings such as an IP address, subnet mask, default gateway and DNS server information.',categories:['Networking'],labs:['network'],keywords:'automatic configuration'},
{id:'dns',term:'DNS',definition:'The Domain Name System translates names such as google.com into IP addresses. Internet connectivity can work by IP even when DNS is unavailable.',categories:['Networking'],labs:['network'],keywords:'domain name hostname'},
{id:'ping',term:'Ping',definition:'A troubleshooting tool using ICMP echo messages to test basic IP reachability. A failed ping does not always mean a destination is offline.',categories:['Networking'],labs:['network'],keywords:'icmp test'},
{id:'power',term:'Power (W)',definition:'The rate at which equipment consumes or produces energy at a particular moment, measured in watts.',categories:['Power'],labs:['power'],keywords:'watts w'},
{id:'energy',term:'Energy (Wh / kWh)',definition:'The amount of energy consumed or produced over time. A 100 W device operating for 10 hours consumes 1 kWh.',categories:['Power'],labs:['power'],keywords:'watt hours wh kwh'},
{id:'battery',term:'Battery capacity (kWh)',definition:'The amount of energy a battery can store. More capacity can keep equipment operating longer when its main source is unavailable.',categories:['Power'],labs:['power'],keywords:'storage'},
{id:'soc',term:'State of Charge (SoC)',definition:'An indication of how much energy remains in a battery, usually expressed as a percentage of usable capacity.',categories:['Power'],labs:['power'],keywords:'battery percent'},
{id:'solar',term:'Solar power',definition:'Electricity generated from sunlight using photovoltaic panels. Generation changes throughout the day.',categories:['Power'],labs:['power'],keywords:'photovoltaic'},
{id:'sun-hours',term:'Peak sun hours',definition:'A simplified way to represent useful solar energy available during a day without assuming panels produce rated power all day.',categories:['Power'],labs:['power'],keywords:'solar generation'},
{id:'efficiency',term:'System efficiency',definition:'The proportion of energy that remains useful after losses in storage, conversion and delivery.',categories:['Power'],labs:['power'],keywords:'losses'},
{id:'poe',term:'Power over Ethernet (PoE)',definition:'A technology carrying electrical power and data over the same Ethernet cable, commonly used for Wi-Fi APs and radios.',categories:['Power','Networking','Wi-Fi'],labs:['wifi','power'],keywords:'ethernet power'},
{id:'capex',term:'CAPEX',definition:'Capital expenditure: the upfront investment required to deploy infrastructure, equipment and other assets.',categories:['Economics & Resilience'],labs:['cost'],keywords:'capital investment cost'},
{id:'opex',term:'OPEX',definition:'Operating expenditure: the recurring costs of running and maintaining a connectivity solution.',categories:['Economics & Resilience'],labs:['cost'],keywords:'operating cost'},
{id:'tco',term:'TCO — Total Cost of Ownership',definition:'The combined cost of owning and operating a solution over a period of time, rather than only its initial cost.',categories:['Economics & Resilience'],labs:['cost'],keywords:'total cost'},
{id:'availability',term:'Availability',definition:'The proportion of time that a service is operational and accessible when needed.',categories:['Economics & Resilience'],labs:['cost','power'],keywords:'uptime'},
{id:'reliability',term:'Reliability',definition:'The ability of a system to continue performing as expected without failures or interruptions.',categories:['Economics & Resilience'],labs:['cost','power'],keywords:'service'},
{id:'resilience',term:'Resilience',definition:'The ability of a connectivity system to withstand disruptions and recover or continue service when something goes wrong.',categories:['Economics & Resilience'],labs:['cost','power'],keywords:'outage continuity'},
{id:'redundancy',term:'Redundancy',definition:'Adding alternative equipment, links or power sources so one failure does not necessarily interrupt service.',categories:['Economics & Resilience'],labs:['cost'],keywords:'backup failover'}];
const LEARN_DISTINCTIONS=[['Wi-Fi ≠ Internet','Wi-Fi connects your device to a local network. That network needs a working upstream connection for Internet access.',['wifi','lan','internet'],['wifi','network']],['Coverage ≠ Capacity','Coverage asks “Can the network reach me?” Capacity asks “Can it support the traffic generated by users?”',['coverage','capacity'],['builder','wifi']],['Power ≠ Energy','Power (W) is the rate of consumption or generation. Energy (Wh/kWh) is the amount over time.',['power','energy'],['power']],['Switch ≠ Router','A switch connects devices within a local network. A router connects different IP networks.',['switch','router'],['network']],['Local traffic ≠ Internet traffic','Same-subnet traffic can stay inside the LAN; remote traffic normally uses the router/default gateway.',['lan','gateway'],['network']],['CAPEX ≠ TCO','CAPEX is upfront investment. TCO includes owning and operating the solution over time, so lowest initial cost is not always lowest long-term cost.',['capex','tco'],['cost']]];

const LEARN_RELATIONS={connectivity:['access-network','backhaul'],backhaul:['fiber','p2p','satellite'],p2p:['los','fresnel','frequency'],wifi:['ap','wifi-bands','wifi-channel','coverage','capacity'],lan:['ethernet','switch','ip-address','subnet'],router:['gateway','wan','internet'],gateway:['router','ip-address','subnet','wan'],dhcp:['ip-address','subnet-mask','gateway','dns'],dns:['ip-address','gateway'],power:['energy','battery','soc','solar','efficiency'],energy:['power','battery','efficiency'],battery:['energy','soc','solar'],capex:['opex','tco'],opex:['capex','tco'],tco:['capex','opex'],reliability:['availability','resilience','redundancy'],availability:['reliability','resilience'],resilience:['reliability','availability','redundancy']};
const LEARN_ACRONYMS={fwa:'FWA',p2p:'P2P',leo:'LEO',los:'LOS',ap:'AP',lan:'LAN',wan:'WAN',ipv4:'IPv4',ipv6:'IPv6',dhcp:'DHCP',dns:'DNS',poe:'PoE',capex:'CAPEX',opex:'OPEX',tco:'TCO',soc:'SoC'};
LEARN_CONCEPTS.forEach(c=>{if(LEARN_ACRONYMS[c.id])c.acronym=LEARN_ACRONYMS[c.id];if(LEARN_RELATIONS[c.id])c.relatedTerms=LEARN_RELATIONS[c.id];});
function learnRelatedLinks(ids){return (ids||[]).map(id=>{const c=LEARN_CONCEPTS.find(x=>x.id===id);return c?'<a href="#learn" data-concept="'+c.id+'">'+c.term+'</a>':''}).filter(Boolean).join(' · ')}
function learnLabLinks(ids){return ids.map(id=>{const l=LABS.find(x=>x.id===id);return l?'<a href="#'+id+'">Lab '+String(LABS.indexOf(l)+1).padStart(2,'0')+'</a>':''}).join(' · ')}
function learnPage(){return '<section class="learn-page"><div class="eyebrow">THE LEARNING LIBRARY</div><h1>Understand the concepts behind L2C</h1><p class="learn-lead">A quick reference for the ideas you encounter while exploring the labs.</p><label class="learn-search">Search concepts...<input id="learn-search" type="search" placeholder="Search concepts..." aria-label="Search concepts"></label><section class="learn-distinctions"><h2>Key distinctions</h2><div class="distinction-grid">'+LEARN_DISTINCTIONS.map(d=>'<article><h3>'+d[0]+'</h3><p>'+d[1]+'</p><small>Explore: '+learnLabLinks(d[3])+'</small><div class="concept-related"><span>Related: </span>'+learnRelatedLinks(d[2])+'</div></article>').join('')+'</div></section><section><h2>Explore concepts</h2><div class="learn-filters" role="toolbar" aria-label="Concept categories">'+LEARN_CATEGORIES.map((c,i)=>'<button type="button" class="learn-filter '+(i===0?'active':'')+'" aria-pressed="'+(i===0?'true':'false')+'" data-category="'+c+'">'+c+'</button>').join('')+'</div><div id="learn-results" class="concept-grid"></div></section></section>';}
function normalizeLearn(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\-\s]/g,'');}
function renderLearnResults(){const q=normalizeLearn(document.getElementById('learn-search')?.value||'');const cat=document.querySelector('.learn-filter.active')?.dataset.category||'All';const list=LEARN_CONCEPTS.filter(c=>(cat==='All'||c.categories.includes(cat))&&(!q||normalizeLearn(c.term+' '+(c.acronym||'')+' '+c.definition+' '+c.keywords).includes(q)));const el=document.getElementById('learn-results');if(!el)return;el.innerHTML=list.length?list.map(c=>'<article class="concept-card" id="concept-'+c.id+'"><h3>'+c.term+(c.acronym?' <small class="concept-acronym">('+c.acronym+')</small>':'')+'</h3><p>'+c.definition+'</p><div class="concept-meta">'+c.categories.map(x=>'<span>'+x+'</span>').join('')+'</div><small>Explore: '+learnLabLinks(c.labs)+'</small>'+(c.relatedTerms?'<div class="concept-related"><span>Related: </span>'+learnRelatedLinks(c.relatedTerms)+'</div>':'')+'</article>').join(''):'<p class="learn-empty">No concepts match that search.</p>';bindLearnRelatedLinks();}
function bindLearnRelatedLinks(){document.querySelectorAll('.concept-related a[data-concept]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();let target=document.getElementById('concept-'+a.dataset.concept);if(!target){const all=document.querySelector('.learn-filter[data-category="All"]');if(all&&!all.classList.contains('active')){all.click();setTimeout(()=>document.getElementById('concept-'+a.dataset.concept)?.scrollIntoView({behavior:'smooth',block:'center'}),0);return;}}if(target)target.scrollIntoView({behavior:'smooth',block:'center'});}));}
function bindLearn(){document.getElementById('learn-search')?.addEventListener('input',renderLearnResults);document.querySelectorAll('.learn-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.learn-filter').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');renderLearnResults()}));renderLearnResults();}